version: '2'
services:
  xml-app:
    image: xml
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://xml-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=XmL
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://xml-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://xml-elasticsearch:9200
    ports:
      - 8080:8080
  xml-mongodb:
    extends:
      file: mongodb.yml
      service: xml-mongodb
  xml-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: xml-elasticsearch
